apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - shlink-namespace.yaml
  - shlink-certificate.yaml
  - shlink-ingress.yaml
  - shlink-back-certificate.yaml
  - shlink-back-ingress.yaml
  - sealed/shlink-db.sealed.yaml
  - sealed/shlink-app.sealed.yaml
  - sealed/ui-basic-auth.sealed.yaml