apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shlink
  namespace: shlink
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: ui-basic-auth
    nginx.ingress.kubernetes.io/auth-secret-type: auth-file
spec:
  ingressClassName: nginx
  tls:
    - secretName: shlink-tls
      hosts:
        - shlink.lv
  rules:
    - host: shlink.lv
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: shlink-shlinkchart-ui
                port:
                  number: 8081