apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shlink-back
  namespace: shlink
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  tls:
    - secretName: shlink-back-tls
      hosts: [back.shlink.lv]
  rules:
    - host: back.shlink.lv
      http:
        paths:
          - path: /rest
            pathType: Prefix
            backend:
              service:
                name: shlink-shlinkchart
                port:
                  number: 8080
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: shlink-shlinkchart
                port:
                  number: 8080
