apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - apps/app-cert-manager.yaml
  - apps/app-cluster-issuer.yaml
  - apps/app-ingress-nginx.yaml
  - apps/app-shlink-helm.yaml
  - apps/app-sealed-secrets.yaml
  - apps/app-mariadb.yaml
  - argocd-ingress.yaml
  - argocd-certificate.yaml
  - argocd-configmap.yaml
  - ../apps/shlink